CREATE
OR REPLACE VIEW erddap."HakaiWatershedsWeatherStations" AS
SELECT
    'WSN693_703' as station,
    51.61058333 as latitude,
    -127.9870833 as longitude,
    449 as elevation,
    measurement_time,
    record,
    wind_spd_ql,
    wind_spd_qc,
    wind_spd_uql,
    wind_spd_avg,
    wind_spd_std,
    wind_dir_ql,
    wind_dir_qc,
    wind_dir_uql,
    wind_dir_avg,
    wind_dir_std,
    rh_ql,
    rh_qc,
    rh_uql,
    rh,
    rh_avg,
    rh_std,
    air_temp_ql,
    air_temp_qc,
    air_temp_uql,
    air_temp,
    air_temp_avg,
    air_temp_std,
    air_temp2_ql,
    air_temp2_qc,
    air_temp2_uql,
    air_temp2,
    air_temp2_avg,
    air_temp2_std,
    rain_ql,
    rain_qc,
    rain_uql,
    rain,
    one_hour_rain_ql,
    one_hour_rain_qc,
    one_hour_rain_uql,
    one_hour_rain,
    snow_depth_ql,
    snow_depth_qc,
    snow_depth_uql,
    snow_depth,
    snow_depth_tc_ql,
    snow_depth_tc_qc,
    snow_depth_tc_uql,
    snow_depth_tc
FROM
    sn.wsn693_703_5minute wsn693_703
UNION
ALL
SELECT
    'WSN626' as station,
    51.62624 as latitude,
    -128.10178 as longitude,
    78 as elevation,
    measurement_time,
    record,
    wind_spd_ql,
    wind_spd_qc,
    wind_spd_uql,
    wind_spd_avg,
    wind_spd_std,
    wind_dir_ql,
    wind_dir_qc,
    wind_dir_uql,
    wind_dir_avg,
    wind_dir_std,
    rh_ql,
    rh_qc,
    rh_uql,
    rh,
    rh_avg,
    rh_std,
    air_temp_ql,
    air_temp_qc,
    air_temp_uql,
    air_temp,
    air_temp_avg,
    air_temp_std,
    air_temp2_ql,
    air_temp2_qc,
    air_temp2_uql,
    air_temp2,
    air_temp2_avg,
    air_temp2_std,
    rain_ql,
    rain_qc,
    rain_uql,
    rain,
    one_hour_rain_ql,
    one_hour_rain_qc,
    one_hour_rain_uql,
    one_hour_rain,
    null as snow_depth_ql,
    null as snow_depth_qc,
    null as snow_depth_uql,
    null as snow_depth,
    null as snow_depth_tc_ql,
    null as snow_depth_tc_qc,
    null as snow_depth_tc_uql,
    null as snow_depth_tc
FROM
    sn.wsn626_5minute wsn626
union
ALL
SELECT
    'SSN693PWR' as station,
    51.64416667 as latitude,
    -127.997778 as longitude,
    51 as elevation,
    measurement_time,
    record,
    wind_spd_ql,
    wind_spd_qc,
    wind_spd_uql,
    wind_spd_avg,
    wind_spd_std,
    wind_dir_ql,
    wind_dir_qc,
    wind_dir_uql,
    wind_dir_avg,
    wind_dir_std,
    rh_ql,
    rh_qc,
    rh_uql,
    rh,
    rh_avg,
    rh_std,
    air_temp_ql,
    air_temp_qc,
    air_temp_uql,
    air_temp,
    air_temp_avg,
    air_temp_std,
    air_temp2_ql,
    air_temp2_qc,
    air_temp2_uql,
    air_temp2,
    air_temp2_avg,
    air_temp2_std,
    rain_ql,
    rain_qc,
    rain_uql,
    rain,
    one_hour_rain_ql,
    one_hour_rain_qc,
    one_hour_rain_uql,
    one_hour_rain,
    null as snow_depth_ql,
    null as snow_depth_qc,
    null as snow_depth_uql,
    null as snow_depth,
    null as snow_depth_tc_ql,
    null as snow_depth_tc_qc,
    null as snow_depth_tc_uql,
    null as snow_depth_tc
FROM
    sn.ssn693pwr_5minute ssn693pwr
UNION
ALL
SELECT
    'WSN703' as station,
    51.64333333 as latitude,
    -128.0227778 as longitude,
    42 as elevation,
    measurement_time,
    record,
    null as wind_spd_ql,
    null as wind_spd_qc,
    null as wind_spd_uql,
    null as wind_spd_avg,
    null as wind_spd_std,
    null as wind_dir_ql,
    null as wind_dir_qc,
    null as wind_dir_uql,
    null as wind_dir_avg,
    null as wind_dir_std,
    rh_ql,
    rh_qc,
    rh_uql,
    rh,
    rh_avg,
    rh_std,
    air_temp_ql,
    air_temp_qc,
    air_temp_uql,
    air_temp,
    air_temp_avg,
    air_temp_std,
    air_temp2_ql,
    air_temp2_qc,
    air_temp2_uql,
    air_temp2,
    air_temp2_avg,
    air_temp2_std,
    rain_ql,
    rain_qc,
    rain_uql,
    rain,
    one_hour_rain_ql,
    one_hour_rain_qc,
    one_hour_rain_uql,
    one_hour_rain,
    null as snow_depth_ql,
    null as snow_depth_qc,
    null as snow_depth_uql,
    null as snow_depth,
    null as snow_depth_tc_ql,
    null as snow_depth_tc_qc,
    null as snow_depth_tc_uql,
    null as snow_depth_tc
FROM
    sn.wsn703_5minute wsn703us
UNION
ALL
SELECT
    'WSN703_708' as station,
    51.62218889 as latitude,
    -128.05065 as longitude,
    289 as elevation,
    measurement_time,
    record,
    wind_spd_ql,
    wind_spd_qc,
    wind_spd_uql,
    wind_spd_avg,
    wind_spd_std,
    wind_dir_ql,
    wind_dir_qc,
    wind_dir_uql,
    wind_dir_avg,
    wind_dir_std,
    rh_ql,
    rh_qc,
    rh_uql,
    rh,
    rh_avg,
    rh_std,
    air_temp_ql,
    air_temp_qc,
    air_temp_uql,
    air_temp,
    air_temp_avg,
    air_temp_std,
    air_temp2_ql,
    air_temp2_qc,
    air_temp2_uql,
    air_temp2,
    air_temp2_avg,
    air_temp2_std,
    rain_ql,
    rain_qc,
    rain_uql,
    rain,
    one_hour_rain_ql,
    one_hour_rain_qc,
    one_hour_rain_uql,
    one_hour_rain,
    snow_depth_ql,
    snow_depth_qc,
    snow_depth_uql,
    snow_depth,
    snow_depth_tc_ql,
    snow_depth_tc_qc,
    snow_depth_tc_uql,
    snow_depth_tc
FROM
    sn.wsn703_708_5minute wsn703_708
UNION
ALL
SELECT
    'SSN708US' as station,
    51.648561 as latitude,
    -128.06835 as longitude,
    12 as elevation,
    measurement_time,
    record,
    null as wind_spd_ql,
    null as wind_spd_qc,
    null as wind_spd_uql,
    null as wind_spd_avg,
    null as wind_spd_std,
    null as wind_dir_ql,
    null as wind_dir_qc,
    null as wind_dir_uql,
    null as wind_dir_avg,
    null as wind_dir_std,
    rh_ql,
    rh_qc,
    rh_uql,
    rh,
    rh_avg,
    rh_std,
    air_temp_ql,
    air_temp_qc,
    air_temp_uql,
    air_temp,
    air_temp_avg,
    air_temp_std,
    air_temp2_ql,
    air_temp2_qc,
    air_temp2_uql,
    air_temp2,
    air_temp2_avg,
    air_temp2_std,
    rain_ql,
    rain_qc,
    rain_uql,
    rain,
    one_hour_rain_ql,
    one_hour_rain_qc,
    one_hour_rain_uql,
    one_hour_rain,
    null as snow_depth_ql,
    null as snow_depth_qc,
    null as snow_depth_uql,
    null as snow_depth,
    null as snow_depth_tc_ql,
    null as snow_depth_tc_qc,
    null as snow_depth_tc_uql,
    null as snow_depth_tc
FROM
    sn.ssn708_5minute ssn708
union
ALL
SELECT
    'SSN819PWR' as station,
    51.66194444 as latitude,
    -128.0419444 as longitude,
    79 as elevation,
    measurement_time,
    record,
    null as wind_spd_ql,
    null as wind_spd_qc,
    null as wind_spd_uql,
    null as wind_spd_avg,
    null as wind_spd_std,
    null as wind_dir_ql,
    null as wind_dir_qc,
    null as wind_dir_uql,
    null as wind_dir_avg,
    null as wind_dir_std,
    rh_ql,
    rh_qc,
    rh_uql,
    rh,
    rh_avg,
    rh_std,
    air_temp_ql,
    air_temp_qc,
    air_temp_uql,
    air_temp,
    air_temp_avg,
    air_temp_std,
    air_temp2_ql,
    air_temp2_qc,
    air_temp2_uql,
    air_temp2,
    air_temp2_avg,
    air_temp2_std,
    rain_ql,
    rain_qc,
    rain_uql,
    rain,
    one_hour_rain_ql,
    one_hour_rain_qc,
    one_hour_rain_uql,
    one_hour_rain,
    null as snow_depth_ql,
    null as snow_depth_qc,
    null as snow_depth_uql,
    null as snow_depth,
    null as snow_depth_tc_ql,
    null as snow_depth_tc_qc,
    null as snow_depth_tc_uql,
    null as snow_depth_tc
FROM
    sn.ssn819pwr_5minute ssn819pwr
union
all
SELECT
    'WSN819_1015' as station,
    51.68265278 as latitude,
    -128.043325 as longitude,
    331 as elevation,
    measurement_time,
    record,
    wind_spd_ql,
    wind_spd_qc,
    wind_spd_uql,
    wind_spd_avg,
    wind_spd_std,
    wind_dir_ql,
    wind_dir_qc,
    wind_dir_uql,
    wind_dir_avg,
    wind_dir_std,
    rh_ql,
    rh_qc,
    rh_uql,
    rh,
    rh_avg,
    rh_std,
    air_temp_ql,
    air_temp_qc,
    air_temp_uql,
    air_temp,
    air_temp_avg,
    air_temp_std,
    air_temp2_ql,
    air_temp2_qc,
    air_temp2_uql,
    air_temp2,
    air_temp2_avg,
    air_temp2_std,
    rain_ql,
    rain_qc,
    rain_uql,
    rain,
    one_hour_rain_ql,
    one_hour_rain_qc,
    one_hour_rain_uql,
    one_hour_rain,
    snow_depth_ql,
    snow_depth_qc,
    snow_depth_uql,
    snow_depth,
    snow_depth_tc_ql,
    snow_depth_tc_qc,
    snow_depth_tc_uql,
    snow_depth_tc
FROM
    sn.wsn819_1015_5minute wsn819_1015
union
ALL
SELECT
    'WSN844' as station,
    51.6613889 as latitude,
    -127.9975 as longitude,
    90 as elevation,
    measurement_time,
    record,
    null as wind_spd_ql,
    null as wind_spd_qc,
    null as wind_spd_uql,
    null as wind_spd_avg,
    null as wind_spd_std,
    null as wind_dir_ql,
    null as wind_dir_qc,
    null as wind_dir_uql,
    null as wind_dir_avg,
    null as wind_dir_std,
    rh_ql,
    rh_qc,
    rh_uql,
    rh,
    rh_avg,
    rh_std,
    air_temp_ql,
    air_temp_qc,
    air_temp_uql,
    air_temp,
    air_temp_avg,
    air_temp_std,
    air_temp2_ql,
    air_temp2_qc,
    air_temp2_uql,
    air_temp2,
    air_temp2_avg,
    air_temp2_std,
    rain_ql,
    rain_qc,
    rain_uql,
    rain,
    one_hour_rain_ql,
    one_hour_rain_qc,
    one_hour_rain_uql,
    one_hour_rain,
    null as snow_depth_ql,
    null as snow_depth_qc,
    null as snow_depth_uql,
    null as snow_depth,
    null as snow_depth_tc_ql,
    null as snow_depth_tc_qc,
    null as snow_depth_tc_uql,
    null as snow_depth_tc
FROM
    sn.wsn844_5minute wsn844
union
ALL
SELECT
    'SSN1015US' as station,
    51.69055556 as latitude,
    -128.0652778 as longitude,
    17 as elevation,
    measurement_time,
    record,
    null as wind_spd_ql,
    null as wind_spd_qc,
    null as wind_spd_uql,
    null as wind_spd_avg,
    null as wind_spd_std,
    null as wind_dir_ql,
    null as wind_dir_qc,
    null as wind_dir_uql,
    null as wind_dir_avg,
    null as wind_dir_std,
    rh_ql,
    rh_qc,
    rh_uql,
    rh,
    rh_avg,
    rh_std,
    air_temp_ql,
    air_temp_qc,
    air_temp_uql,
    air_temp,
    air_temp_avg,
    air_temp_std,
    air_temp2_ql,
    air_temp2_qc,
    air_temp2_uql,
    air_temp2,
    air_temp2_avg,
    air_temp2_std,
    rain_ql,
    rain_qc,
    rain_uql,
    rain,
    one_hour_rain_ql,
    one_hour_rain_qc,
    one_hour_rain_uql,
    one_hour_rain,
    null as snow_depth_ql,
    null as snow_depth_qc,
    null as snow_depth_uql,
    null as snow_depth,
    null as snow_depth_tc_ql,
    null as snow_depth_tc_qc,
    null as snow_depth_tc_uql,
    null as snow_depth_tc
FROM
    sn.ssn1015us_5minute ssn1015us
union
all
SELECT
    'hecate' as station,
    51.682567 as latitude,
    -128.022783 as longitude,
    477 as elevation,
    measurement_time,
    record,
    wind_spd_ql,
    wind_spd_qc,
    wind_spd_uql,
    wind_spd_avg,
    wind_spd_std,
    wind_dir_ql,
    wind_dir_qc,
    wind_dir_uql,
    wind_dir_avg,
    wind_dir_std,
    rh_ql,
    rh_qc,
    rh_uql,
    rh,
    rh_avg,
    rh_std,
    air_temp_ql,
    air_temp_qc,
    air_temp_uql,
    air_temp,
    air_temp_avg,
    air_temp_std,
    air_temp2_ql,
    air_temp2_qc,
    air_temp2_uql,
    air_temp2,
    air_temp2_avg,
    air_temp2_std,
    rain_ql,
    rain_qc,
    rain_uql,
    rain,
    one_hour_rain_ql,
    one_hour_rain_qc,
    one_hour_rain_uql,
    one_hour_rain,
    snow_depth_ql,
    snow_depth_qc,
    snow_depth_uql,
    snow_depth,
    snow_depth_tc_ql,
    snow_depth_tc_qc,
    snow_depth_tc_uql,
    snow_depth_tc
FROM
    sn.hecate_5minute hecate
union
all
SELECT
    'buxton_east' as station,
    51.589936 as latitude,
    -127.975236 as longitude,
    740 as elevation,
    measurement_time,
    record,
    wind_spd_ql,
    wind_spd_qc,
    wind_spd_uql,
    wind_spd_avg,
    wind_spd_std,
    wind_dir_ql,
    wind_dir_qc,
    wind_dir_uql,
    wind_dir_avg,
    wind_dir_std,
    rh_ql,
    rh_qc,
    rh_uql,
    rh,
    rh_avg,
    rh_std,
    air_temp_ql,
    air_temp_qc,
    air_temp_uql,
    air_temp,
    air_temp_avg,
    air_temp_std,
    air_temp2_ql,
    air_temp2_qc,
    air_temp2_uql,
    air_temp2,
    air_temp2_avg,
    air_temp2_std,
    rain_ql,
    rain_qc,
    rain_uql,
    rain,
    one_hour_rain_ql,
    one_hour_rain_qc,
    one_hour_rain_uql,
    one_hour_rain,
    snow_depth_ql,
    snow_depth_qc,
    snow_depth_uql,
    snow_depth,
    snow_depth_tc_ql,
    snow_depth_tc_qc,
    snow_depth_tc_uql,
    snow_depth_tc
FROM
    sn.buxton_east_5minute buxton_east
union
ALL
SELECT
    'buxton' as station,
    51.60491 as latitude,
    -128.017822 as longitude,
    672 as elevation,
    measurement_time,
    record,
    wind_spd_ql,
    wind_spd_qc,
    wind_spd_uql,
    wind_spd_avg,
    wind_spd_std,
    wind_dir_ql,
    wind_dir_qc,
    wind_dir_uql,
    wind_dir_avg,
    wind_dir_std,
    rh_ql,
    rh_qc,
    rh_uql,
    rh,
    rh_avg,
    rh_std,
    air_temp_ql,
    air_temp_qc,
    air_temp_uql,
    air_temp,
    air_temp_avg,
    air_temp_std,
    air_temp2_ql,
    air_temp2_qc,
    air_temp2_uql,
    air_temp2,
    air_temp2_avg,
    air_temp2_std,
    null as rain_ql,
    null as rain_qc,
    null as rain_uql,
    null as rain,
    null as one_hour_rain_ql,
    null as one_hour_rain_qc,
    null as one_hour_rain_uql,
    null as one_hour_rain,
    null as snow_depth_ql,
    null as snow_depth_qc,
    null as snow_depth_uql,
    null as snow_depth,
    null as snow_depth_tc_ql,
    null as snow_depth_tc_qc,
    null as snow_depth_tc_uql,
    null as snow_depth_tc
FROM
    sn.buxton_5minute buxton
union
ALL
SELECT
    'ref_stn' as station,
    51.65195 as latitude,
    -128.1287 as longitude,
    43 as elevation,
    measurement_time,
    record,
    wind_spd_ql,
    wind_spd_qc,
    wind_spd_uql,
    wind_spd_avg,
    wind_spd_std,
    wind_dir_ql,
    wind_dir_qc,
    wind_dir_uql,
    wind_dir_avg,
    wind_dir_std,
    rh_ql,
    rh_qc,
    rh_uql,
    rh,
    rh_avg,
    rh_std,
    air_temp_ql,
    air_temp_qc,
    air_temp_uql,
    air_temp,
    air_temp_avg,
    air_temp_std,
    air_temp2_ql,
    air_temp2_qc,
    air_temp2_uql,
    air_temp2,
    air_temp2_avg,
    air_temp2_std,
    rain_ql,
    rain_qc,
    rain_uql,
    rain,
    one_hour_rain_ql,
    one_hour_rain_qc,
    one_hour_rain_uql,
    one_hour_rain,
    snow_depth_ql,
    snow_depth_qc,
    snow_depth_uql,
    snow_depth,
    snow_depth_tc_ql,
    snow_depth_tc_qc,
    snow_depth_tc_uql,
    snow_depth_tc
FROM
    sn.ref_stn_5minute ref_stn
union
all
SELECT
    'lookout' as station,
    51.6475 as latitude,
    -128.143183 as longitude,
    63 as elevation,
    measurement_time,
    record,
    wind_spd_ql,
    wind_spd_qc,
    wind_spd_uql,
    wind_spd_avg,
    wind_spd_std,
    wind_dir_ql,
    wind_dir_qc,
    wind_dir_uql,
    wind_dir_avg,
    wind_dir_std,
    rh_ql,
    rh_qc,
    rh_uql,
    rh,
    rh_avg,
    rh_std,
    air_temp_ql,
    air_temp_qc,
    air_temp_uql,
    air_temp,
    air_temp_avg,
    air_temp_std,
    air_temp2_ql,
    air_temp2_qc,
    air_temp2_uql,
    air_temp2,
    air_temp2_avg,
    air_temp2_std,
    rain_ql,
    rain_qc,
    rain_uql,
    rain,
    null as one_hour_rain_ql,
    null as one_hour_rain_qc,
    null as one_hour_rain_uql,
    null as one_hour_rain,
    null as snow_depth_ql,
    null as snow_depth_qc,
    null as snow_depth_uql,
    null as snow_depth,
    null as snow_depth_tc_ql,
    null as snow_depth_tc_qc,
    null as snow_depth_tc_uql,
    null as snow_depth_tc
FROM
    sn.lookout_5minute lookout
union
ALL
SELECT
    'ethel' as station,
    51.548443 as latitude,
    -127.531748 as longitude,
    3 as elevation,
    measurement_time,
    record,
    wind_spd_ql,
    wind_spd_qc,
    wind_spd_uql,
    wind_spd_avg,
    wind_spd_std,
    wind_dir_ql,
    wind_dir_qc,
    wind_dir_uql,
    wind_dir_avg,
    wind_dir_std,
    rh_ql,
    rh_qc,
    rh_uql,
    rh,
    rh_avg,
    rh_std,
    air_temp_ql,
    air_temp_qc,
    air_temp_uql,
    air_temp,
    air_temp_avg,
    air_temp_std,
    air_temp2_ql,
    air_temp2_qc,
    air_temp2_uql,
    air_temp2,
    air_temp2_avg,
    air_temp2_std,
    rain_ql,
    rain_qc,
    rain_uql,
    rain,
    one_hour_rain_ql,
    one_hour_rain_qc,
    one_hour_rain_uql,
    one_hour_rain,
    null as snow_depth_ql,
    null as snow_depth_qc,
    null as snow_depth_uql,
    null as snow_depth,
    null as snow_depth_tc_ql,
    null as snow_depth_tc_qc,
    null as snow_depth_tc_uql,
    null as snow_depth_tc
FROM
    sn.ethel_5minute ethel
union
ALL
SELECT
    'quadra' as station,
    50.1162556 as latitude,
    -125.2221111 as longitude,
    11 as elevation,
    measurement_time,
    record,
    wind_spd_ql,
    wind_spd_qc,
    wind_spd_uql,
    wind_spd_avg,
    wind_spd_std,
    wind_dir_ql,
    wind_dir_qc,
    wind_dir_uql,
    wind_dir_avg,
    wind_dir_std,
    rh_ql,
    rh_qc,
    rh_uql,
    rh,
    rh_avg,
    rh_std,
    air_temp_ql,
    air_temp_qc,
    air_temp_uql,
    air_temp,
    air_temp_avg,
    air_temp_std,
    air_temp2_ql,
    air_temp2_qc,
    air_temp2_uql,
    air_temp2,
    air_temp2_avg,
    air_temp2_std,
    rain_ql,
    rain_qc,
    rain_uql,
    rain,
    one_hour_rain_ql,
    one_hour_rain_qc,
    one_hour_rain_uql,
    one_hour_rain,
    null as snow_depth_ql,
    null as snow_depth_qc,
    null as snow_depth_uql,
    null as snow_depth,
    null as snow_depth_tc_ql,
    null as snow_depth_tc_qc,
    null as snow_depth_tc_uql,
    null as snow_depth_tc
FROM
    sn.quadra_5minute quadra;