CREATE
OR REPLACE VIEW erddap.HakaiWatershedsStreamStations AS
SELECT
    *
FROM
    (
        SELECT
            'SSN626US' as station,
            51.64081 as latitude,
            -128.12065 as longitude,
            8 as elevation,
            measurement_time,
            record,
            pls_lvl_ql,
            pls_lvl_qc,
            pls_lvl_uql,
            pls_lvl,
            pls_lvl_avg,
            pls_lvl_min,
            pls_lvl_max,
            pls_lvl_std,
            pls_temp_ql,
            pls_temp_qc,
            pls_temp_uql,
            pls_temp,
            pls_temp_avg,
            pls_temp_min,
            pls_temp_max,
            pls_temp_std,
            discharge_rate_ql,
            discharge_rate_qc,
            discharge_rate_uql,
            discharge_rate,
            discharge_rate_min,
            discharge_rate_max,
            discharge_volume_ql,
            discharge_volume_qc,
            discharge_volume_uql,
            discharge_volume,
            discharge_volume_min,
            discharge_volume_max,
            turbidity_ql,
            turbidity_qc,
            turbidity_uql,
            turbidity_med,
            turbidity_avg,
            turbidity_ntu_ql,
            turbidity_ntu_qc,
            turbidity_ntu_uql,
            turbidity_ntu_med,
            turbidity_ntu_avg
        FROM
            sn.ssn626us_5minute ssn626us
        union
        SELECT
            'SSN693US' as station,
            51.645 as latitude,
            -127.9977778 as longitude,
            51 as elevation,
            measurement_time,
            record,
            pls_lvl_ql,
            pls_lvl_qc,
            pls_lvl_uql,
            pls_lvl,
            pls_lvl_avg,
            pls_lvl_min,
            pls_lvl_max,
            pls_lvl_std,
            pls_temp_ql,
            pls_temp_qc,
            pls_temp_uql,
            pls_temp,
            pls_temp_avg,
            pls_temp_min,
            pls_temp_max,
            pls_temp_std,
            discharge_rate_ql,
            discharge_rate_qc,
            discharge_rate_uql,
            discharge_rate,
            discharge_rate_min,
            discharge_rate_max,
            discharge_volume_ql,
            discharge_volume_qc,
            discharge_volume_uql,
            discharge_volume,
            discharge_volume_min,
            discharge_volume_max,
            null as turbidity_ql,
            null as turbidity_qc,
            null as turbidity_uql,
            null as turbidity_med,
            null as turbidity_avg,
            null as turbidity_ntu_ql,
            null as turbidity_ntu_qc,
            null as turbidity_ntu_uql,
            null as turbidity_ntu_med,
            null as turbidity_ntu_avg
        FROM
            sn.ssn693us_5minute ssn693us
        union
        SELECT
            'SSN703US' as station,
            51.646612 as latitude,
            -128.025715 as longitude,
            40 as elevation,
            measurement_time,
            record,
            pls_lvl_ql,
            pls_lvl_qc,
            pls_lvl_uql,
            pls_lvl,
            pls_lvl_avg,
            pls_lvl_min,
            pls_lvl_max,
            pls_lvl_std,
            pls_temp_ql,
            pls_temp_qc,
            pls_temp_uql,
            pls_temp,
            pls_temp_avg,
            pls_temp_min,
            pls_temp_max,
            pls_temp_std,
            discharge_rate_ql,
            discharge_rate_qc,
            discharge_rate_uql,
            discharge_rate,
            discharge_rate_min,
            discharge_rate_max,
            discharge_volume_ql,
            discharge_volume_qc,
            discharge_volume_uql,
            discharge_volume,
            discharge_volume_min,
            discharge_volume_max,
            null as turbidity_ql,
            null as turbidity_qc,
            null as turbidity_uql,
            null as turbidity_med,
            null as turbidity_avg,
            null as turbidity_ntu_ql,
            null as turbidity_ntu_qc,
            null as turbidity_ntu_uql,
            null as turbidity_ntu_med,
            null as turbidity_ntu_avg
        FROM
            sn.ssn693us_5minute ssn693us
        union
        SELECT
            'SSN703US' as station,
            51.64333333 as latitude,
            -128.0227778 as longitude,
            42 as elevation,
            measurement_time,
            record,
            pls_lvl_ql,
            pls_lvl_qc,
            pls_lvl_uql,
            pls_lvl,
            pls_lvl_avg,
            pls_lvl_min,
            pls_lvl_max,
            pls_lvl_std,
            pls_temp_ql,
            pls_temp_qc,
            pls_temp_uql,
            pls_temp,
            pls_temp_avg,
            pls_temp_min,
            pls_temp_max,
            pls_temp_std,
            discharge_rate_ql,
            discharge_rate_qc,
            discharge_rate_uql,
            discharge_rate,
            discharge_rate_min,
            discharge_rate_max,
            discharge_volume_ql,
            discharge_volume_qc,
            discharge_volume_uql,
            discharge_volume,
            discharge_volume_min,
            discharge_volume_max,
            turbidity_ql,
            turbidity_qc,
            turbidity_uql,
            turbidity_med,
            turbidity_avg,
            turbidity_ntu_ql,
            turbidity_ntu_qc,
            turbidity_ntu_uql,
            turbidity_ntu_med,
            turbidity_ntu_avg
        FROM
            sn.ssn703us_5minute ssn703us
        union
        SELECT
            'SSN708' as station,
            51.648561 as latitude,
            -128.06835 as longitude,
            12 as elevation,
            measurement_time,
            record,
            pls_lvl_ql,
            pls_lvl_qc,
            pls_lvl_uql,
            pls_lvl,
            pls_lvl_avg,
            pls_lvl_min,
            pls_lvl_max,
            pls_lvl_std,
            pls_temp_ql,
            pls_temp_qc,
            pls_temp_uql,
            pls_temp,
            pls_temp_avg,
            pls_temp_min,
            pls_temp_max,
            pls_temp_std,
            discharge_rate_ql,
            discharge_rate_qc,
            discharge_rate_uql,
            discharge_rate,
            discharge_rate_min,
            discharge_rate_max,
            discharge_volume_ql,
            discharge_volume_qc,
            discharge_volume_uql,
            discharge_volume,
            discharge_volume_min,
            discharge_volume_max,
            turbidity_ql,
            turbidity_qc,
            turbidity_uql,
            turbidity_med,
            turbidity_avg,
            turbidity_ntu_ql,
            turbidity_ntu_qc,
            turbidity_ntu_uql,
            turbidity_ntu_med,
            turbidity_ntu_avg
        FROM
            sn.ssn708_5minute ssn708
        union
        SELECT
            'SSN844US' as station,
            51.66083333 as latitude,
            -128.0025 as longitude,
            35 as elevation,
            measurement_time,
            record,
            pls_lvl_ql,
            pls_lvl_qc,
            pls_lvl_uql,
            pls_lvl,
            pls_lvl_avg,
            pls_lvl_min,
            pls_lvl_max,
            pls_lvl_std,
            pls_temp_ql,
            pls_temp_qc,
            pls_temp_uql,
            pls_temp,
            pls_temp_avg,
            pls_temp_min,
            pls_temp_max,
            pls_temp_std,
            discharge_rate_ql,
            discharge_rate_qc,
            discharge_rate_uql,
            discharge_rate,
            discharge_rate_min,
            discharge_rate_max,
            discharge_volume_ql,
            discharge_volume_qc,
            discharge_volume_uql,
            discharge_volume,
            discharge_volume_min,
            discharge_volume_max,
            turbidity_ql,
            turbidity_qc,
            turbidity_uql,
            turbidity_med,
            turbidity_avg,
            turbidity_ntu_ql,
            turbidity_ntu_qc,
            turbidity_ntu_uql,
            turbidity_ntu_med,
            turbidity_ntu_avg
        FROM
            sn.ssn844us_5minute ssn844us
        union
        SELECT
            'SSN1015US' as station,
            51.69055556 as latitude,
            -128.0652778 as longitude,
            17 as elevation,
            measurement_time,
            record,
            pls_lvl_ql,
            pls_lvl_qc,
            pls_lvl_uql,
            pls_lvl,
            pls_lvl_avg,
            pls_lvl_min,
            pls_lvl_max,
            pls_lvl_std,
            pls_temp_ql,
            pls_temp_qc,
            pls_temp_uql,
            pls_temp,
            pls_temp_avg,
            pls_temp_min,
            pls_temp_max,
            pls_temp_std,
            discharge_rate_ql,
            discharge_rate_qc,
            discharge_rate_uql,
            discharge_rate,
            discharge_rate_min,
            discharge_rate_max,
            discharge_volume_ql,
            discharge_volume_qc,
            discharge_volume_uql,
            discharge_volume,
            discharge_volume_min,
            discharge_volume_max,
            turbidity_ql,
            turbidity_qc,
            turbidity_uql,
            turbidity_med,
            turbidity_avg,
            turbidity_ntu_ql,
            turbidity_ntu_qc,
            turbidity_ntu_uql,
            turbidity_ntu_med,
            turbidity_ntu_avg
        FROM
            sn.ssn1015us_5minute ssn1015us
    ) as data;