CREATE
OR REPLACE VIEW erddap."HakaiKCBuoy1hour" AS
SELECT
    "measurementTime",
    "KCBuoy:WindSpd_QL",
    "KCBuoy:WindSpd_QC",
    "KCBuoy:WindSpd_UQL",
    "KCBuoy:WindSpd_Avg",
    "KCBuoy:WindSpd_Min",
    "KCBuoy:WindSpd_Max",
    "KCBuoy:WindSpd_Std",
    "KCBuoy:WindDir_QL",
    "KCBuoy:WindDir_QC",
    "KCBuoy:WindDir_UQL",
    "KCBuoy:WindDir_Avg",
    "KCBuoy:WindDir_Std",
    "KCBuoy:AirTemp_QL",
    "KCBuoy:AirTemp_QC",
    "KCBuoy:AirTemp_UQL",
    "KCBuoy:AirTemp",
    "KCBuoy:AirTemp_Med",
    "KCBuoy:AirTemp_Avg",
    "KCBuoy:AirTemp_Min",
    "KCBuoy:AirTemp_Max",
    "KCBuoy:StationAirPressure_QL",
    "KCBuoy:StationAirPressure_QC",
    "KCBuoy:StationAirPressure_UQL",
    "KCBuoy:StationAirPressure",
    "KCBuoy:StationAirPressure_Avg",
    "KCBuoy:StationAirPressure_Min",
    "KCBuoy:StationAirPressure_Max",
    "KCBuoy:StationAirPressure_Std",
    "KCBuoy:EnclosureTemp_Avg",
    "KCBuoy:EnclosureTemp_Min",
    "KCBuoy:EnclosureTemp_Max",
    "KCBuoy:PanelTemp_Avg",
    "KCBuoy:PanelTemp_Min",
    "KCBuoy:PanelTemp_Max",
    "KCBuoy:BattVolt_Avg",
    "KCBuoy:BattVolt_Min",
    "KCBuoy:BattVolt_Max",
    "KCBuoy:WaterTemp_QL",
    "KCBuoy:WaterTemp_QC",
    "KCBuoy:WaterTemp_UQL",
    "KCBuoy:WaterTemp",
    "KCBuoy:WaterTemp_Med",
    "KCBuoy:WaterTemp_Avg",
    "KCBuoy:WaterTemp_Min",
    "KCBuoy:WaterTemp_Max",
    "KCBuoy:WaterConductivity_QL",
    "KCBuoy:WaterConductivity_QC",
    "KCBuoy:WaterConductivity_UQL",
    "KCBuoy:WaterConductivity",
    "KCBuoy:WaterConductivity_Med",
    "KCBuoy:WaterConductivity_Avg",
    "KCBuoy:WaterConductivity_Min",
    "KCBuoy:WaterConductivity_Max",
    "KCBuoy:WaterPressure_QL",
    "KCBuoy:WaterPressure_QC",
    "KCBuoy:WaterPressure_UQL",
    "KCBuoy:WaterPressure",
    "KCBuoy:WaterPressure_Med",
    "KCBuoy:WaterPressure_Avg",
    "KCBuoy:WaterPressure_Min",
    "KCBuoy:WaterPressure_Max",
    "KCBuoy:WaterSalinity_QL",
    "KCBuoy:WaterSalinity_QC",
    "KCBuoy:WaterSalinity_UQL",
    "KCBuoy:WaterSalinity",
    "KCBuoy:WaterSalinity_Med",
    "KCBuoy:WaterSalinity_Avg",
    "KCBuoy:WaterSalinity_Min",
    "KCBuoy:WaterSalinity_Max",
    "KCBuoy:OxygenConcentration_QC",
    "KCBuoy:OxygenConcentration_QL",
    "KCBuoy:OxygenConcentration_UQL",
    "KCBuoy:OxygenConcentration",
    "KCBuoy:OxygenConcentration_Med",
    "KCBuoy:OxygenConcentration_Avg",
    "KCBuoy:OxygenConcentration_Min",
    "KCBuoy:OxygenConcentration_Max",
    COALESCE("KCBuoy:Fluorometer_QC", "KCBuoy:Chlorophyll_QC") AS "KCBuoy:Fluorometer_QC",
    COALESCE("KCBuoy:Fluorometer_QL", "KCBuoy:Chlorophyll_QL") AS "KCBuoy:Fluorometer_QL",
    COALESCE("KCBuoy:Fluorometer_UQL", "KCBuoy:Chlorophyll_UQL") AS "KCBuoy:Fluorometer_UQL",
    COALESCE("KCBuoy:Fluorometer", "KCBuoy:Chlorophyll") AS "KCBuoy:Fluorometer",
    COALESCE("KCBuoy:Fluorometer_Med", "KCBuoy:Chlorophyll_Med") AS "KCBuoy:Fluorometer_Med",
    COALESCE("KCBuoy:Fluorometer_Avg", "KCBuoy:Chlorophyll_Avg") AS "KCBuoy:Fluorometer_Avg",
    COALESCE("KCBuoy:Fluorometer_Min", "KCBuoy:Chlorophyll_Min") AS "KCBuoy:Fluorometer_Min",
    COALESCE("KCBuoy:Fluorometer_Max", "KCBuoy:Chlorophyll_Max") AS "KCBuoy:Fluorometer_Max",
    "KCBuoy:Latitude",
    "KCBuoy:Latitude_Med",
    "KCBuoy:Latitude_Avg",
    "KCBuoy:Latitude_Min",
    "KCBuoy:Latitude_Max",
    "KCBuoy:Longitude",
    "KCBuoy:Longitude_Med",
    "KCBuoy:Longitude_Avg",
    "KCBuoy:Longitude_Min",
    "KCBuoy:Longitude_Max",
    "KCBuoy:Pitch",
    "KCBuoy:Pitch_Med",
    "KCBuoy:Pitch_Avg",
    "KCBuoy:Pitch_Min",
    "KCBuoy:Pitch_Max",
    "KCBuoy:Roll",
    "KCBuoy:Roll_Med",
    "KCBuoy:Roll_Avg",
    "KCBuoy:Roll_Min",
    "KCBuoy:Roll_Max",
    "KCSeaology:sw_xCO2_QL",
    "KCSeaology:sw_xCO2_QC",
    "KCSeaology:sw_xCO2_UQL",
    "KCSeaology:sw_xCO2",
    "KCSeaology:atm_xCO2_QL",
    "KCSeaology:atm_xCO2_QC",
    "KCSeaology:atm_xCO2_UQL",
    "KCSeaology:atm_xCO2",
    "KCSeaology:zeroPostCal",
    "KCSeaology:spanPostCal",
    "KCSeaology:spanPressurePumpOn",
    "KCSeaology:spanPressurePumpOff",
    "KCSeaology:deltaSpanPressure",
    "KCSeaology:deltaZeroPressure",
    "KCSeaology:deltaEQPressure",
    "KCSeaology:deltaAirPressure",
    "KCSeaology:equilPumpOffO2",
    "KCSeaology:equilPumpOffRH",
    "KCSeaology:airPumpOffO2",
    "KCSeaology:airPumpOffRH"
FROM
    sn."KCBuoyCombined:1hourSamples"
WHERE
    "measurementTime" > (
        NOW() - '60 days'::INTERVAL
    )
ORDER BY
    "measurementTime" DESC;
