RewriteEngine On
# --- Rule to display the challenge page ---
# IF the 'cf_turnstile_token' cookie is NOT present
# AND the request is for an existing file
# AND the request is within the protected '/erddap/files/' directory
# THEN rewrite the user to the directory index, which should display the Turnstile challenge.
RewriteCond %{HTTP_COOKIE} !cf_turnstile_token
RewriteCond %{REQUEST_URI} ^/erddap/files/ [NC]
RewriteCond %{REQUEST_URI} \..+$ [NC]
RewriteRule ^/erddap/files/(.+) /erddap/files/ [R,L]

# --- Rule to proxy the file for verified users ---
# IF the 'cf_turnstile_token' cookie IS present
# AND the request is for an existing file
# AND the request is within the protected '/erddap/files/' directory
# THEN rewrite the request to the verification proxy.
RewriteCond %{HTTP_COOKIE} cf_turnstile_token=([^;]+) [NC]
RewriteCond %{REQUEST_URI} ^/erddap/files/ [NC]
RewriteCond %{REQUEST_URI} \..+$ [NC]
RewriteRule ^(.*)$ /cf/proxy/$1 [R,L]


<location /erddap>
    AuthType Basic
    AuthName "Restricted Content"
    Include /etc/apache2/github_actions_ips.txt
    AuthUserFile /etc/apache2/.htaccess-erddap
    Require valid-user

    Header set Content-Security-Policy "script-src 'self' 'unsafe-inline' 'unsafe-eval' plausible.server.hakai.app www.googletagmanager.com challenges.cloudflare.com;"
    Header set Access-Control-Allow-Origin *
    ProxyPreserveHost On
    ProxyPass http://localhost:8082/erddap
    ProxyPassReverse http://localhost:8082/erddap
</location>

<location /cf>
    ProxyPreserveHost On
    ProxyPass http://localhost:9988
    ProxyPassReverse http://localhost:9988
</location>

<location /cdn-cgi/challenge-platform/>
    RequestHeader set Host "cdn.loopedin.io"
    ProxyPass https://cdn.loopedin.io/cdn-cgi/challenge-platform/
    ProxyPassReverse https://cdn.loopedin.io/cdn-cgi/challenge-platform/
</location>