name: Deploy Nginx Image to GHCR

on:
  push:
    paths:
      - nginx/**
    branches:
      - portainer
  workflow_dispatch:

jobs:
      push-nginx-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './hakai_erddap_nginx_proxy'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
            registry: ghcr.io
            username: hakai-it
            password: ${{ secrets.CI_TOKEN }}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/hakaiinstitute/hakai_erddap_nginx_proxy:latest
              docker push ghcr.io/hakaiinstitute/hakai_erddap_nginx_proxy:latest
