name: Update Development ERDDAP server
on:
  push:
    branches:
      - development
  workflow_run:
    workflows: [Test datasets.xml and linter]
    types:
      - completed
jobs:
  development-update:
    name: Update ERDDAP
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://development.erddap.hakai.app/erddap/
    steps:
      - name: Update development server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USERNAME }}
          passphrase: ${{ secrets.DEV_SERVER_PASSPHRASE }}
          key: ${{ secrets.DEV_SERVER_SSH_KEY }}
          script: cd  ~/hakai-erddap-dev/; CONTAINER_NAME=$(sudo docker ps -q -f name="erddap_dev\.") bash update-erddap.sh --hardFlag